[project]
name = "simpleworkspace"
version = "1.2.27"
description = "Package created for https://spacerival.com, opensource and free to use and modify"
requires-python = ">=3.10"
dependencies = [ "requests",]

[build-system]
requires = [ "setuptools",]
build-backend = "setuptools.build_meta"
