[tool.poetry]
name = "wcpan-drive-crypt"
version = "4.0.0a0"
description = "crypt middleware for wcpan.drive"
authors = ["Wei-Cheng Pan <legnaleurc@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "wcpan"}]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.18.0"
wcpan-drive-core = {version = "^4.0.0a7", allow-prereleases = true}

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
