[project]
name = "smcore"
version = "0.0.66"
authors = [
        {name="J. Hoffman, J. Genender", email="johnmarianhoffman@gmail.com"},
]
description = "Package providing base sm agent classes and clients"
readme= "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "protobuf == 4.21.12",
	"pycurl == 7.45.2",
]

[project.urls]
"Homepage" = "https://gitlab.com/hoffman-lab/core"
"Bug Tracker" = "https://gitlab.com/hoffman-lab/core/issues"
"Changelog - Python" = "https://gitlab.com/hoffman-lab/core/-/blob/main/python/pkg/CHANGELOG.md?ref_type=heads"
"Changelog - Project" = "https://gitlab.com/hoffman-lab/core/-/blob/main/CHANGELOG.md?ref_type=heads"
