[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "arts"
version = "2023.12.11"
description = "对 Python 开发中常用功能的封装"
dependencies = ["motor", "pymongo", "aiomysql", "pymysql", "openai>=1.2.4", "pycryptodome", "tornado", "numpy"]

readme = "README.md"
authors = [{name = "lcctoor.com", email = "lcctoor@outlook.com"}]

[project.urls]
HomePage = "https://github.com/lcctoor/arts/tree/main/arts"