[project]
name = "simpleworkspace"
version = "1.2.23"
description = "Package created for https://spacerival.com, opensource and free to use and modify"
requires-python = ">=3.10"
dependencies = [ "requests",]

[build-system]
requires = [ "setuptools", "wheel", "twine",]
build-backend = "setuptools.build_meta"
